version: "3.9"

networks:
    laravel:
        name: laravel

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        depends_on:
            - php
            - mysql
        container_name: nginx
        ports:
            - 9000:80
            - 443:443
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./backend:/var/www/html
            # - ./frontend:/var/www/html/spa
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./backend:/var/www/html
        networks:
            - laravel

    mysql:
        image: mysql:8.0.27
        platform: linux/amd64
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laraveldb
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

    composer:
        image: composer
        volumes:
          - ./backend:/var/www/html
        command: composer install
        depends_on:
          - php
        networks:
          - laravel

    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./backend:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['php', 'artisan']
        networks:
            - laravel

    # npm:
    #     image: node:latest
    #     volumes:
    #       - ./frontend:/var/www/html/spa
    #     working_dir: /var/www/html/spa
    #     command: npm install && npm run build
    #     networks:
    #       - laravel
